#!/usr/bin/env python3
"""Generate the shared 120px boot/sleep bitmap from the CrossHatch artwork."""

from pathlib import Path

from convert_icon import image_to_c_array, load_image


ROOT = Path(__file__).resolve().parents[1]


def main():
    # Reuse the icon converter's portrait rotation and white=1 bitmap packing.
    image = load_image(str(ROOT / "src/images/crosshatch.png"), 120, 120)
    header = image_to_c_array(image, "Logo120")
    header = header.replace(
        "// size: 120x120",
        "// Generated by scripts/generate_boot_logo.py from src/images/crosshatch.png.\n"
        "// size: 120x120",
    )
    header += 'static_assert(sizeof(Logo120) == 1800, "Logo120 must be exactly 120x120 / 8 bytes");\n'
    header = "\n".join(line.rstrip() for line in header.splitlines()) + "\n"
    (ROOT / "src/images/Logo120.h").write_text(header)


if __name__ == "__main__":
    main()
